# Generated by Django 5.0.6 on 2024-05-13 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('category', models.CharField(max_length=50, verbose_name='product category')),
                ('description', models.CharField(max_length=50, verbose_name='product description')),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='product price')),
                ('image', models.ImageField(height_field=1080, upload_to='media/images/products', verbose_name='product image', width_field=1080)),
            ],
        ),
    ]
