# Generated by Django 5.0.6 on 2024-05-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=models.IntegerField(blank=True, null=True), upload_to='media/images/products', verbose_name='image', width_field=models.IntegerField(blank=True, null=True)),
        ),
    ]
