# Generated by Django 5.0.6 on 2024-05-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image_height_product_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=models.IntegerField(blank=True, null=True), upload_to='images/products/', verbose_name='image', width_field=models.IntegerField(blank=True, null=True)),
        ),
    ]
