# Generated by Django 5.0.6 on 2024-05-20 15:12

import address.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_paid", models.BooleanField(verbose_name="has paid")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("ESEWA", "Esewa"),
                            ("COD", "Cash On Delivery"),
                            ("KHALTI", "Khalti"),
                            ("BANK TRANSFER", "Bank Transfer"),
                        ],
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "billing_address",
                    address.models.AddressField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_address",
                        to="address.address",
                    ),
                ),
                (
                    "shipping_address",
                    address.models.AddressField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ship_address",
                        to="address.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing",
                "verbose_name_plural": "Billings",
            },
        ),
    ]
