# Generated by Django 5.0.6 on 2024-05-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_created_at_alter_cart_customer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitems",
            options={"verbose_name": "CartItem", "verbose_name_plural": "Cart Items"},
        ),
    ]
