# Generated by Django 5.0.6 on 2024-05-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitems_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="cart.cart",
                verbose_name="cart",
            ),
        ),
    ]
