# Generated by Django 5.0.6 on 2024-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(blank=True, default=1080, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(blank=True, default=1080, null=True),
        ),
    ]
