# Generated by Django 5.0.6 on 2024-05-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='sc name')),
                ('Catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catalog', verbose_name='Sub Catalog')),
            ],
        ),
    ]
