# Generated by Django 5.0.6 on 2024-05-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatalog',
            name='Catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catalog', verbose_name='Catalog'),
        ),
        migrations.AlterField(
            model_name='subcatalog',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Sub Catalog'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('image_width', models.IntegerField(default=1080)),
                ('image_height', models.IntegerField(default=1080)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='images/products/', verbose_name='image', width_field='image_width')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcatalog', verbose_name='Category')),
            ],
        ),
    ]
